@extends('layouts.front')
@section('content')



<div class="container d-flex justify-content-center mt-4 mb-4">
            <div class="login-wrapper login-shadow bg-white mt-4 mb-4 col-md-8  ">
                <div class="login-wrapper-flex  ">
                    <div class="p-4">
                        <h2 class="single-title text-center mb-4">La politique de confidentialité </h2>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><em><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>En vigueur au 01/03/2022</span></em></p>
                        <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'>
                            <ol style="margin-bottom:0cm;list-style-type: decimal;margin-left:26px;">
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Arial","sans-serif";'>D&eacute;finitions:</span></strong></li>
                            </ol>
                        </div>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'><br> <strong>Client :</strong> tout professionnel ou personne physique capable au sens des articles 1123 et suivants du Code civil, ou personne morale, qui visite le Site objet des pr&eacute;sentes conditions g&eacute;n&eacute;rales.<br> <strong>Prestations et Services:</strong> https://www.ethix-invest.com met &agrave; disposition des Clients</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><strong><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Contenu :</span></strong><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>&nbsp;Ensemble des &eacute;l&eacute;ments constituants l&rsquo;information pr&eacute;sente sur le Site, notamment textes &ndash; images &ndash; vid&eacute;os.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><strong><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Informations clients :</span></strong><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>&nbsp;Ci-apr&egrave;s d&eacute;nomm&eacute; &laquo; Information (s) &raquo; qui correspondent &agrave; l&rsquo;ensemble des donn&eacute;es personnelles susceptibles d&rsquo;&ecirc;tre d&eacute;tenues par https://www.ethix-invest.com pour la gestion de votre compte, de la gestion de la relation client et &agrave; des fins d&rsquo;analyses et de statistiques.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><strong><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Utilisateur :</span></strong><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>&nbsp;Internaute se connectant, utilisant le site susnomm&eacute;. &laquo; Les informations qui permettent, sous quelque forme que ce soit, directement ou non, l&rsquo;identification des personnes physiques auxquelles elles s&rsquo;appliquent &raquo; (article 4 de la loi n&deg; 78-17 du 6 janvier 1978).<br>&nbsp;Les termes &laquo; donn&eacute;es &agrave; caract&egrave;re personnel &raquo;, &laquo; personne concern&eacute;e &raquo;, &laquo; sous-traitant &raquo; et &laquo; donn&eacute;es sensibles &raquo; ont le sens d&eacute;fini par le R&egrave;glement G&eacute;n&eacute;ral sur la Protection des Donn&eacute;es (RGPD : n&deg; 2016-679)</span></p>
                        <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'>
                            <ol style="margin-bottom:0cm;list-style-type: undefined;margin-left:26px;">
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Arial","sans-serif";'>Pr&eacute;sentation du site internet.</span></strong></li>
                            </ol>
                        </div>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'><br>&nbsp;En vertu de l&rsquo;article 6 de la loi n&deg; 2004-575 du 21 juin 2004 pour la confiance dans l&rsquo;&eacute;conomie num&eacute;rique, il est pr&eacute;cis&eacute; aux utilisateurs du site internet https://www.ethix-invest.com l&rsquo;identit&eacute; des diff&eacute;rents intervenants dans le cadre de sa r&eacute;alisation et de son suivi :<br> <strong>Propri&eacute;taire</strong> : SAS ETHIX-INVEST au Capital social de 1000&euro; &ndash; domicili&eacute; au 12 Rue des Chauffours 95000 Cergy</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><strong><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Responsable publication</span></strong><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>&nbsp;: SAS Ethix-invest &ndash; contact@ethix-invest.com<br>&nbsp;Le responsable publication est une personne physique ou une personne morale.<br> <strong>H&eacute;bergeur</strong> : ovh &ndash; 2 rue Kellermann 59100 Roubaix 1007<br> <strong>D&eacute;l&eacute;gu&eacute; &agrave; la protection des donn&eacute;es</strong> : SAS Ethix-invest &ndash; contact@ethix-invest.com</span></p>
                        <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'>
                            <ol style="margin-bottom:0cm;list-style-type: undefined;margin-left:26px;">
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Arial","sans-serif";'>Conditions g&eacute;n&eacute;rales d&rsquo;utilisation du site et des services propos&eacute;s.</span></strong></li>
                            </ol>
                        </div>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Le Site constitue une &oelig;uvre de l&rsquo;esprit prot&eacute;g&eacute;e par les dispositions du Code de la Propri&eacute;t&eacute; Intellectuelle et des R&eacute;glementations Internationales applicables.<br>&nbsp;Le Client ne peut en aucune mani&egrave;re r&eacute;utiliser, c&eacute;der ou exploiter pour son propre compte tout ou partie des &eacute;l&eacute;ments ou travaux du Site.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>L&rsquo;utilisation du site https://www.ethix-invest.com implique l&rsquo;acceptation pleine et enti&egrave;re des conditions g&eacute;n&eacute;rales d&rsquo;utilisation ci-apr&egrave;s d&eacute;crites. Ces conditions d&rsquo;utilisation sont susceptibles d&rsquo;&ecirc;tre modifi&eacute;es ou compl&eacute;t&eacute;es &agrave; tout moment, les utilisateurs du site https://www.ethix-invest.com sont donc invit&eacute;s &agrave; les consulter de mani&egrave;re r&eacute;guli&egrave;re.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Ce site internet est normalement accessible &agrave; tout moment aux utilisateurs. Une interruption pour raison de maintenance technique peut &ecirc;tre toutefois d&eacute;cid&eacute;e par https://www.ethix-invest.com, qui s&rsquo;efforcera alors de communiquer pr&eacute;alablement aux utilisateurs les dates et heures de l&rsquo;intervention.<br>&nbsp;Le site web https://www.ethix-invest.com est mis &agrave; jour r&eacute;guli&egrave;rement. De la m&ecirc;me fa&ccedil;on, les mentions l&eacute;gales peuvent &ecirc;tre modifi&eacute;es &agrave; tout moment : elles s&rsquo;imposent n&eacute;anmoins &agrave; l&rsquo;utilisateur qui est invit&eacute; &agrave; s&rsquo;y r&eacute;f&eacute;rer le plus souvent possible afin d&rsquo;en prendre connaissance.</span></p>
                        <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'>
                            <ol style="margin-bottom:0cm;list-style-type: undefined;margin-left:26px;">
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Arial","sans-serif";'>Description des services fournis.</span></strong></li>
                            </ol>
                        </div>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Le site internet https://www.ethix-invest.com. a pour objet de fournir une information concernant l&rsquo;ensemble des activit&eacute;s de la soci&eacute;t&eacute;.<br>&nbsp;https://www.ethix-invest.com s&rsquo;efforce de fournir sur le site https://www.ethix-invest.com des informations aussi pr&eacute;cises que possible. Toutefois, il ne pourra &ecirc;tre tenu responsable des oublis, des inexactitudes et des carences dans la mise &agrave; jour, qu&rsquo;elles soient de son fait ou du fait des tiers partenaires qui lui fournissent ces informations.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Toutes les informations indiqu&eacute;es sur le site https://www.ethix-invest.com sont donn&eacute;es &agrave; titre indicatif, et sont susceptibles d&rsquo;&eacute;voluer. Par ailleurs, les renseignements figurant sur le site https://www.ethix-invest.com ne sont pas exhaustifs. Ils sont donn&eacute;s sous r&eacute;serve de modifications ayant &eacute;t&eacute; apport&eacute;es depuis leur mise en ligne.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Limitations contractuelles sur les donn&eacute;es techniques. Le site utilise la technologie JavaScript.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Le site Internet ne pourra &ecirc;tre tenu responsable de dommages mat&eacute;riels li&eacute;s &agrave; l&rsquo;utilisation du site. De plus, l&rsquo;utilisateur du site s&rsquo;engage &agrave; acc&eacute;der au site en utilisant un mat&eacute;riel r&eacute;cent, ne contenant pas de virus et avec un navigateur de derni&egrave;re g&eacute;n&eacute;ration mis-&agrave;-jour<br>&nbsp;Le site https://www.ethix-invest.comest h&eacute;berg&eacute; chez un prestataire sur le territoire de l&rsquo;Union Europ&eacute;enne conform&eacute;ment aux dispositions du R&egrave;glement G&eacute;n&eacute;ral sur la Protection des Donn&eacute;es (RGPD : n&deg; 2016-679)</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>L&rsquo;objectif est d&rsquo;apporter une prestation qui assure le meilleur taux d&rsquo;accessibilit&eacute;. L&rsquo;h&eacute;bergeur assure la continuit&eacute; de son service 24 Heures sur 24, tous les jours de l&rsquo;ann&eacute;e. Il se r&eacute;serve n&eacute;anmoins la possibilit&eacute; d&rsquo;interrompre le service d&rsquo;h&eacute;bergement pour les dur&eacute;es les plus courtes possibles notamment &agrave; des fins de maintenance, d&rsquo;am&eacute;lioration de ses infrastructures, de d&eacute;faillance de ses infrastructures ou si les Prestations et Services g&eacute;n&egrave;rent un trafic r&eacute;put&eacute; anormal.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>https://www.ethix-invest.com et l&rsquo;h&eacute;bergeur ne pourront &ecirc;tre tenus responsables en cas de dysfonctionnement du r&eacute;seau Internet, des lignes t&eacute;l&eacute;phoniques ou du mat&eacute;riel informatique et de t&eacute;l&eacute;phonie li&eacute; notamment &agrave; l&rsquo;encombrement du r&eacute;seau emp&ecirc;chant l&rsquo;acc&egrave;s au serveur.</span></p>
                        <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'>
                            <ol style="margin-bottom:0cm;list-style-type: undefined;margin-left:26px;">
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Arial","sans-serif";'>Propri&eacute;t&eacute; intellectuelle et contrefa&ccedil;ons.</span></strong></li>
                            </ol>
                        </div>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>https://www.ethix-invest.com est propri&eacute;taire des droits de propri&eacute;t&eacute; intellectuelle et d&eacute;tient les droits d&rsquo;usage sur tous les &eacute;l&eacute;ments accessibles sur le site internet, notamment les textes, images, graphismes, logos, vid&eacute;os, ic&ocirc;nes et sons.<br>&nbsp;Toute reproduction, repr&eacute;sentation, modification, publication, adaptation de tout ou partie des &eacute;l&eacute;ments du site, quel que soit le moyen ou le proc&eacute;d&eacute; utilis&eacute;, est interdite, sauf autorisation &eacute;crite pr&eacute;alable de https://www.ethix-invest.com</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Toute exploitation non autoris&eacute;e du site ou de l&rsquo;un quelconque des &eacute;l&eacute;ments qu&rsquo;il contient sera consid&eacute;r&eacute;e comme constitutive d&rsquo;une contrefa&ccedil;on et poursuivie conform&eacute;ment aux dispositions des articles L.335-2 et suivants du Code de Propri&eacute;t&eacute; Intellectuelle.</span></p>
                        <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'>
                            <ol style="margin-bottom:0cm;list-style-type: undefined;margin-left:26px;">
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Arial","sans-serif";'>Limitations de responsabilit&eacute;.</span></strong></li>
                            </ol>
                        </div>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>https://www.ethix-invest.com agit en tant qu&rsquo;&eacute;diteur du site. https://www.ethix-invest.com est responsable de la qualit&eacute; et de la v&eacute;racit&eacute; du Contenu qu&rsquo;il publie.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>https://www.ethix-invest.com ne pourra &ecirc;tre tenu responsable des dommages directs et indirects caus&eacute;s au mat&eacute;riel de l&rsquo;utilisateur, lors de l&rsquo;acc&egrave;s au site internet https://www.ethix-invest.com, et r&eacute;sultant soit de l&rsquo;utilisation d&rsquo;un mat&eacute;riel ne r&eacute;pondant pas aux sp&eacute;cifications indiqu&eacute;es au point 4, soit de l&rsquo;apparition d&rsquo;un bug ou d&rsquo;une incompatibilit&eacute;.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>https://www.ethix-invest.com ne pourra &eacute;galement &ecirc;tre tenu responsable des dommages indirects (tels par exemple qu&rsquo;une perte de march&eacute; ou perte d&rsquo;une chance) cons&eacute;cutifs &agrave; l&rsquo;utilisation du site https://www.ethix-invest.com.<br>&nbsp;Des espaces interactifs (possibilit&eacute; de poser des questions dans l&rsquo;espace contact) sont &agrave; la disposition des utilisateurs. https://www.ethix-invest.com se r&eacute;serve le droit de supprimer, sans mise en demeure pr&eacute;alable, tout contenu d&eacute;pos&eacute; dans cet espace qui contreviendrait &agrave; la l&eacute;gislation applicable en France, en particulier aux dispositions relatives &agrave; la protection des donn&eacute;es. Le cas &eacute;ch&eacute;ant, https://www.ethix-invest.com se r&eacute;serve &eacute;galement la possibilit&eacute; de mettre en cause la responsabilit&eacute; civile et/ou p&eacute;nale de l&rsquo;utilisateur, notamment en cas de message &agrave; caract&egrave;re raciste, injurieux, diffamant, ou pornographique, quel que soit le support utilis&eacute; (texte, photographie &hellip;).</span></p>
                        <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'>
                            <ol style="margin-bottom:0cm;list-style-type: undefined;margin-left:26px;">
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Arial","sans-serif";'>Gestion des donn&eacute;es personnelles.</span></strong></li>
                            </ol>
                        </div>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Le Client est inform&eacute; des r&eacute;glementations concernant la communication marketing, la loi du 21 Juin 2014 pour la confiance dans l&rsquo;Economie Num&eacute;rique, la Loi Informatique et Libert&eacute; du 06 Ao&ucirc;t 2004 ainsi que du R&egrave;glement G&eacute;n&eacute;ral sur la Protection des Donn&eacute;es (RGPD : n&deg; 2016-679).</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><strong><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>7.1 Responsables de la collecte des donn&eacute;es personnelles</span></strong></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Pour les Donn&eacute;es Personnelles collect&eacute;es dans le cadre de la cr&eacute;ation du compte personnel de l&rsquo;Utilisateur et de sa navigation sur le Site, le responsable du traitement des Donn&eacute;es Personnelles est : SAS ETHIX-INVEST. https://www.ethix-invest.com est repr&eacute;sent&eacute; par Sabrina ISSAD, son repr&eacute;sentant l&eacute;gal</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>En tant que responsable du traitement des donn&eacute;es qu&rsquo;il collecte, https://www.ethix-invest.com s&rsquo;engage &agrave; respecter le cadre des dispositions l&eacute;gales en vigueur. Il lui appartient notamment au Client d&rsquo;&eacute;tablir les finalit&eacute;s de ses traitements de donn&eacute;es, de fournir &agrave; ses prospects et clients, &agrave; partir de la collecte de leurs consentements, une information compl&egrave;te sur le traitement de leurs donn&eacute;es personnelles et de maintenir un registre des traitements conforme &agrave; la r&eacute;alit&eacute;.<br>&nbsp;Chaque fois que https://www.ethix-invest.com traite des Donn&eacute;es Personnelles, https//:www.ethix-invest.com prend toutes les mesures raisonnables pour s&rsquo;assurer de l&rsquo;exactitude et de la pertinence des Donn&eacute;es Personnelles au regard des finalit&eacute;s pour lesquelles https://www.ethix-invest.com les traite.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><strong><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>7.2 Finalit&eacute; des donn&eacute;es collect&eacute;es</span></strong></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>https://www.ethix-invest.com est susceptible de traiter tout ou partie des donn&eacute;es :</span></p>
                        <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";color:black;text-align:justify;vertical-align:baseline;'><span style='font-size:10px;font-family:"Arial","sans-serif";'>pour permettre la navigation sur le Site et la gestion et la tra&ccedil;abilit&eacute; des prestations et services command&eacute;s par l&rsquo;utilisateur : donn&eacute;es de connexion et d&rsquo;utilisation du Site, facturation, historique des commandes, etc.</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";color:black;text-align:justify;vertical-align:baseline;'><span style='font-size:10px;font-family:"Arial","sans-serif";'>pour pr&eacute;venir et lutter contre la fraude informatique (spamming, hacking&hellip;) : mat&eacute;riel informatique utilis&eacute; pour la navigation, l&rsquo;adresse IP, le mot de passe (hash&eacute;)</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";color:black;text-align:justify;vertical-align:baseline;'><span style='font-size:10px;font-family:"Arial","sans-serif";'>pour am&eacute;liorer la navigation sur le Site : donn&eacute;es de connexion et d&rsquo;utilisation pour mener des enqu&ecirc;tes de satisfaction facultatives sur https://www.ethix-invest.com : adresse email</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";color:black;text-align:justify;vertical-align:baseline;'><span style='font-size:10px;font-family:"Arial","sans-serif";'>pour mener des campagnes de communication (sms, mail) : num&eacute;ro de t&eacute;l&eacute;phone, adresse email<br>&nbsp;https://www.ethix-invest.com ne commercialise pas vos donn&eacute;es personnelles qui sont donc uniquement utilis&eacute;es par n&eacute;cessit&eacute; ou &agrave; des fins statistiques et d&rsquo;analyses.</span></li>
                        </ul>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><strong><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>7.3 Droit d&rsquo;acc&egrave;s, de rectification et d&rsquo;opposition</span></strong></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'><br>&nbsp;Conform&eacute;ment &agrave; la r&eacute;glementation europ&eacute;enne en vigueur, les Utilisateurs de https://www.ethix-invest.com disposent des droits suivants :</span></p>
                        <ul style="margin-bottom:0cm;margin-top:0cm;" type="disc">
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";color:black;text-align:justify;vertical-align:baseline;'><span style='font-size:10px;font-family:"Arial","sans-serif";'>droit d&rsquo;acc&egrave;s (article 15 RGPD) et de rectification (article 16 RGPD), de mise &agrave; jour, de compl&eacute;tude des donn&eacute;es des Utilisateurs.</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";color:black;text-align:justify;vertical-align:baseline;'><span style='font-size:10px;font-family:"Arial","sans-serif";'>droit de verrouillage ou d&rsquo;effacement des donn&eacute;es des Utilisateurs &agrave; caract&egrave;re personnel (article 17 du RGPD), lorsqu&rsquo;elles sont inexactes, incompl&egrave;tes, &eacute;quivoques, p&eacute;rim&eacute;es, ou dont la collecte, l&rsquo;utilisation, la communication ou la conservation est interdite</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";color:black;text-align:justify;vertical-align:baseline;'><span style='font-size:10px;font-family:"Arial","sans-serif";'>droit de retirer &agrave; tout moment un consentement (article 13-2c RGPD)</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";color:black;text-align:justify;vertical-align:baseline;'><span style='font-size:10px;font-family:"Arial","sans-serif";'>droit &agrave; la limitation du traitement des donn&eacute;es des Utilisateurs (article 18 RGPD)</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";color:black;text-align:justify;vertical-align:baseline;'><span style='font-size:10px;font-family:"Arial","sans-serif";'>droit d&rsquo;opposition au traitement des donn&eacute;es des Utilisateurs (article 21 RGPD)</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";color:black;text-align:justify;vertical-align:baseline;'><span style='font-size:10px;font-family:"Arial","sans-serif";'>droit &agrave; la portabilit&eacute; des donn&eacute;es que les Utilisateurs auront fournies, lorsque ces donn&eacute;es font l&rsquo;objet de traitements automatis&eacute;s fond&eacute;s sur leur consentement ou sur un contrat (article 20 RGPD)</span></li>
                            <li style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";color:black;text-align:justify;vertical-align:baseline;'><span style='font-size:10px;font-family:"Arial","sans-serif";'>droit de d&eacute;finir le sort des donn&eacute;es des Utilisateurs apr&egrave;s leur mort et de choisir &agrave; qui https://www.ethix-invest.com devra communiquer (ou non) ses donn&eacute;es &agrave; un tiers qu&rsquo;ils aura pr&eacute;alablement d&eacute;sign&eacute;</span></li>
                        </ul>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>D&egrave;s que https://www.ethix-invest.com a connaissance du d&eacute;c&egrave;s d&rsquo;un Utilisateur et &agrave; d&eacute;faut d&rsquo;instructions de sa part, https://www.ethix-invest.com s&rsquo;engage &agrave; d&eacute;truire ses donn&eacute;es, sauf si leur conservation s&rsquo;av&egrave;re n&eacute;cessaire &agrave; des fins probatoires ou pour r&eacute;pondre &agrave; une obligation l&eacute;gale.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Si l&rsquo;Utilisateur souhaite savoir comment https://www.ethix-invest.com utilise ses Donn&eacute;es Personnelles, demander &agrave; les rectifier ou s&rsquo;oppose &agrave; leur traitement, l&rsquo;Utilisateur peut contacter https://www.ethix-invest.com par &eacute;crit &agrave; l&rsquo;adresse suivante :</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>SAS ETHIX-INVEST &ndash; DPO, Ethix-invest<br>&nbsp;12 Rue des Chauffours 95000 cERGY</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Dans ce cas, l&rsquo;Utilisateur doit indiquer les Donn&eacute;es Personnelles qu&rsquo;il souhaiterait que https://www.ethix-invest.com corrige, mette &agrave; jour ou supprime, en s&rsquo;identifiant pr&eacute;cis&eacute;ment avec une copie d&rsquo;une pi&egrave;ce d&rsquo;identit&eacute; (carte d&rsquo;identit&eacute; ou passeport).</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Les demandes de suppression de Donn&eacute;es Personnelles seront soumises aux obligations qui sont impos&eacute;es &agrave; https://www.ethix-invest.com par la loi, notamment en mati&egrave;re de conservation ou d&rsquo;archivage des documents. Enfin, les Utilisateurs de https://www.ethix-invest.com peuvent d&eacute;poser une r&eacute;clamation aupr&egrave;s des autorit&eacute;s de contr&ocirc;le, et notamment de la CNIL (https://www.cnil.fr/fr/plaintes).</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><strong><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>7.4 Non-communication des donn&eacute;es personnelles</span></strong></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>https://www.ethix-invest.com s&rsquo;interdit de traiter, h&eacute;berger ou transf&eacute;rer les Informations collect&eacute;es sur ses Clients vers un pays situ&eacute; en dehors de l&rsquo;Union europ&eacute;enne ou reconnu comme &laquo; non ad&eacute;quat &raquo; par la Commission europ&eacute;enne sans en informer pr&eacute;alablement le client. Pour autant, https://www.ethix-invest.com reste libre du choix de ses sous-traitants techniques et commerciaux &agrave; la condition qu&rsquo;il pr&eacute;sente les garanties suffisantes au regard des exigences du R&egrave;glement G&eacute;n&eacute;ral sur la Protection des Donn&eacute;es (RGPD : n&deg; 2016-679).</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>https://www.ethix-invest.com s&rsquo;engage &agrave; prendre toutes les pr&eacute;cautions n&eacute;cessaires afin de pr&eacute;server la s&eacute;curit&eacute; des Informations et notamment qu&rsquo;elles ne soient pas communiqu&eacute;es &agrave; des personnes non autoris&eacute;es. Cependant, si un incident impactant l&rsquo;int&eacute;grit&eacute; ou la confidentialit&eacute; des Informations du Client est port&eacute;e &agrave; la connaissance de https://www.ethix-invest.com, celle-ci devra dans les meilleurs d&eacute;lais informer le Client et lui communiquer les mesures de corrections prises. Par ailleurs https://www.ethix-invest.com ne collecte aucune &laquo; donn&eacute;es sensibles &raquo;.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Les Donn&eacute;es Personnelles de l&rsquo;Utilisateur peuvent &ecirc;tre trait&eacute;es par des filiales de https://www.ethix-invest.com et des sous-traitants (prestataires de services), exclusivement afin de r&eacute;aliser les finalit&eacute;s de la pr&eacute;sente politique.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Dans la limite de leurs attributions respectives et pour les finalit&eacute;s rappel&eacute;es ci-dessus, les principales personnes susceptibles d&rsquo;avoir acc&egrave;s aux donn&eacute;es des Utilisateurs de https://www.ethix-invest.com sont principalement les agents de notre service client.</span></p>
                        <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'>
                            <ol style="margin-bottom:0cm;list-style-type: undefined;margin-left:26px;">
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Arial","sans-serif";'>Notification d&rsquo;incident</span></strong></li>
                            </ol>
                        </div>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Quels que soient les efforts fournis, aucune m&eacute;thode de transmission sur Internet et aucune m&eacute;thode de stockage &eacute;lectronique n&rsquo;est compl&egrave;tement s&ucirc;re. Nous ne pouvons en cons&eacute;quence pas garantir une s&eacute;curit&eacute; absolue.<br>&nbsp;Si nous prenions connaissance d&rsquo;une br&egrave;che de la s&eacute;curit&eacute;, nous avertirions les utilisateurs concern&eacute;s afin qu&rsquo;ils puissent prendre les mesures appropri&eacute;es. Nos proc&eacute;dures de notification d&rsquo;incident tiennent compte de nos obligations l&eacute;gales, qu&rsquo;elles se situent au niveau national ou europ&eacute;en. Nous nous engageons &agrave; informer pleinement nos clients de toutes les questions relevant de la s&eacute;curit&eacute; de leur compte et &agrave; leur fournir toutes les informations n&eacute;cessaires pour les aider &agrave; respecter leurs propres obligations r&eacute;glementaires en mati&egrave;re de reporting.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Aucune information personnelle de l&rsquo;utilisateur du site https://www.ethix-invest.com n&rsquo;est publi&eacute;e &agrave; l&rsquo;insu de l&rsquo;utilisateur, &eacute;chang&eacute;e, transf&eacute;r&eacute;e, c&eacute;d&eacute;e ou vendue sur un support quelconque &agrave; des tiers. Seule l&rsquo;hypoth&egrave;se du rachat de https://www.ethix-invest.com et de ses droits permettrait la transmission des dites informations &agrave; l&rsquo;&eacute;ventuel acqu&eacute;reur qui serait &agrave; son tour tenu de la m&ecirc;me obligation de conservation et de modification des donn&eacute;es vis &agrave; vis de l&rsquo;utilisateur du site https://www.ethix-invest.com</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Pour assurer la s&eacute;curit&eacute; et la confidentialit&eacute; des Donn&eacute;es Personnelles et des Donn&eacute;es Personnelles de Sant&eacute;, https://www.ethix-invest.com utilise des r&eacute;seaux prot&eacute;g&eacute;s par des dispositifs standards tels que par pare-feu, la pseudonymisation, l&rsquo;encryption et mot de passe.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Lors du traitement des Donn&eacute;es Personnelles, https://www.ethix-invest.com prend toutes les mesures raisonnables visant &agrave; les prot&eacute;ger contre toute perte, utilisation d&eacute;tourn&eacute;e, acc&egrave;s non autoris&eacute;, divulgation, alt&eacute;ration ou destruction.</span></p>
                        <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'>
                            <ol style="margin-bottom:0cm;list-style-type: undefined;margin-left:26px;">
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Arial","sans-serif";'>Liens hypertextes &laquo; cookies &raquo; et balises (&ldquo;tags&rdquo;) internet</span></strong></li>
                            </ol>
                        </div>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'><br>&nbsp;Le site https://www.ethix-invest.com contient un certain nombre de liens hypertextes vers d&rsquo;autres sites, mis en place avec l&rsquo;autorisation de https://www.ethix-invest.com. Cependant, https://www.ethix-invest.com n&rsquo;a pas la possibilit&eacute; de v&eacute;rifier le contenu des sites ainsi visit&eacute;s, et n&rsquo;assumera en cons&eacute;quence aucune responsabilit&eacute; de ce fait.<br>&nbsp;Sauf si vous d&eacute;cidez de d&eacute;sactiver les cookies, vous acceptez que le site puisse les utiliser. Vous pouvez &agrave; tout moment d&eacute;sactiver ces cookies et ce gratuitement &agrave; partir des possibilit&eacute;s de d&eacute;sactivation qui vous sont offertes et rappel&eacute;es ci-apr&egrave;s, sachant que cela peut r&eacute;duire ou emp&ecirc;cher l&rsquo;accessibilit&eacute; &agrave; tout ou partie des Services propos&eacute;s par le site.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><strong><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>9.1. &laquo; COOKIES &raquo;</span></strong></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Un &laquo; cookie &raquo; est un petit fichier d&rsquo;information envoy&eacute; sur le navigateur de l&rsquo;Utilisateur et enregistr&eacute; au sein du terminal de l&rsquo;Utilisateur (ex : ordinateur, smartphone), (ci-apr&egrave;s &laquo; Cookies &raquo;). Ce fichier comprend des informations telles que le nom de domaine de l&rsquo;Utilisateur, le fournisseur d&rsquo;acc&egrave;s Internet de l&rsquo;Utilisateur, le syst&egrave;me d&rsquo;exploitation de l&rsquo;Utilisateur, ainsi que la date et l&rsquo;heure d&rsquo;acc&egrave;s. Les Cookies ne risquent en aucun cas d&rsquo;endommager le terminal de l&rsquo;Utilisateur.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>https://www.ethix-invest.com est susceptible de traiter les informations de l&rsquo;Utilisateur concernant sa visite du Site, telles que les pages consult&eacute;es, les recherches effectu&eacute;es. Ces informations permettent &agrave; https://www.ethix-invest.com d&rsquo;am&eacute;liorer le contenu du Site, de la navigation de l&rsquo;Utilisateur.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Les Cookies facilitant la navigation et/ou la fourniture des services propos&eacute;s par le Site, l&rsquo;Utilisateur peut configurer son navigateur pour qu&rsquo;il lui permette de d&eacute;cider s&rsquo;il souhaite ou non les accepter de mani&egrave;re &agrave; ce que des Cookies soient enregistr&eacute;s dans le terminal ou, au contraire, qu&rsquo;ils soient rejet&eacute;s, soit syst&eacute;matiquement, soit selon leur &eacute;metteur. L&rsquo;Utilisateur peut &eacute;galement configurer son logiciel de navigation de mani&egrave;re &agrave; ce que l&rsquo;acceptation ou le refus des Cookies lui soient propos&eacute;s ponctuellement, avant qu&rsquo;un Cookie soit susceptible d&rsquo;&ecirc;tre enregistr&eacute; dans son terminal. https://www.ethix-invest.com informe l&rsquo;Utilisateur que, dans ce cas, il se peut que les fonctionnalit&eacute;s de son logiciel de navigation ne soient pas toutes disponibles.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Si l&rsquo;Utilisateur refuse l&rsquo;enregistrement de Cookies dans son terminal ou son navigateur, ou si l&rsquo;Utilisateur supprime ceux qui y sont enregistr&eacute;s, l&rsquo;Utilisateur est inform&eacute; que sa navigation et son exp&eacute;rience sur le Site peuvent &ecirc;tre limit&eacute;es. Cela pourrait &eacute;galement &ecirc;tre le cas lorsque https://www.ethix-invest.com ou l&rsquo;un de ses prestataires ne peut pas reconna&icirc;tre, &agrave; des fins de compatibilit&eacute; technique, le type de navigateur utilis&eacute; par le terminal, les param&egrave;tres de langue et d&rsquo;affichage ou le pays depuis lequel le terminal semble connect&eacute; &agrave; Internet.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Le cas &eacute;ch&eacute;ant, https://www.ethix-invest.com d&eacute;cline toute responsabilit&eacute; pour les cons&eacute;quences li&eacute;es au fonctionnement d&eacute;grad&eacute; du Site et des services &eacute;ventuellement propos&eacute;s par https://www.ethix-invest.com, r&eacute;sultant (i) du refus de Cookies par l&rsquo;Utilisateur (ii) de l&rsquo;impossibilit&eacute; pour https://www.ethix-invest.com d&rsquo;enregistrer ou de consulter les Cookies n&eacute;cessaires &agrave; leur fonctionnement du fait du choix de l&rsquo;Utilisateur. Pour la gestion des Cookies et des choix de l&rsquo;Utilisateur, la configuration de chaque navigateur est diff&eacute;rente. Elle est d&eacute;crite dans le menu d&rsquo;aide du navigateur, qui permettra de savoir de quelle mani&egrave;re l&rsquo;Utilisateur peut modifier ses souhaits en mati&egrave;re de Cookies.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>&Agrave; tout moment, l&rsquo;Utilisateur peut faire le choix d&rsquo;exprimer et de modifier ses souhaits en mati&egrave;re de Cookies. https://www.ethix-invest.com pourra en outre faire appel aux services de prestataires externes pour l&rsquo;aider &agrave; recueillir et traiter les informations d&eacute;crites dans cette section.<br>&nbsp;Enfin, en cliquant sur les ic&ocirc;nes d&eacute;di&eacute;es aux r&eacute;seaux sociaux Twitter, Facebook, Linkedin et Google Plus figurant sur le Site de https://www.ethix-invest.com ou dans son application mobile et si l&rsquo;Utilisateur a accept&eacute; le d&eacute;p&ocirc;t de cookies en poursuivant sa navigation sur le Site Internet ou l&rsquo;application mobile de https://www.ethix-invest.com, Twitter, Facebook, Linkedin et Google Plus peuvent &eacute;galement d&eacute;poser des cookies sur vos terminaux (ordinateur, tablette, t&eacute;l&eacute;phone portable).<br>&nbsp;Ces types de cookies ne sont d&eacute;pos&eacute;s sur vos terminaux qu&rsquo;&agrave; condition que vous y consentiez, en continuant votre navigation sur le Site Internet ou l&rsquo;application mobile de https://www.ethix-invest.com. &Agrave; tout moment, l&rsquo;Utilisateur peut n&eacute;anmoins revenir sur son consentement &agrave; ce que https://www.ethix-invest.com d&eacute;pose ce type de cookies.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><strong><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Article 9.2. BALISES (&ldquo;TAGS&rdquo;) INTERNET</span></strong></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>https://www.ethix-invest.com peut employer occasionnellement des balises Internet (&eacute;galement appel&eacute;es &laquo; tags &raquo;, ou balises d&rsquo;action, GIF &agrave; un pixel, GIF transparents, GIF invisibles et GIF un &agrave; un) et les d&eacute;ployer par l&rsquo;interm&eacute;diaire d&rsquo;un partenaire sp&eacute;cialiste d&rsquo;analyses Web susceptible de se trouver (et donc de stocker les informations correspondantes, y compris l&rsquo;adresse IP de l&rsquo;Utilisateur) dans un pays &eacute;tranger.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Ces balises sont plac&eacute;es &agrave; la fois dans les publicit&eacute;s en ligne permettant aux internautes d&rsquo;acc&eacute;der au Site, et sur les diff&eacute;rentes pages de celui-ci.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'>Cette technologie permet &agrave; https://www.ethix-invest.com d&rsquo;&eacute;valuer les r&eacute;ponses des visiteurs face au Site et l&rsquo;efficacit&eacute; de ses actions (par exemple, le nombre de fois o&ugrave; une page est ouverte et les informations consult&eacute;es), ainsi que l&rsquo;utilisation de ce Site par l&rsquo;Utilisateur.<br>&nbsp;Le prestataire externe pourra &eacute;ventuellement recueillir des informations sur les visiteurs du Site et d&rsquo;autres sites Internet gr&acirc;ce &agrave; ces balises, constituer des rapports sur l&rsquo;activit&eacute; du Site &agrave; l&rsquo;attention de https://www.ethix-invest.com, et fournir d&rsquo;autres services relatifs &agrave; l&rsquo;utilisation de celui-ci et d&rsquo;Internet.</span></p>
                        <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'>
                            <ol style="margin-bottom:0cm;list-style-type: undefined;margin-left:26px;">
                                <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'><strong><span style='font-family:"Arial","sans-serif";'>Droit applicable et attribution de juridiction.</span></strong></li>
                            </ol>
                        </div>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:normal;font-size:15px;font-family:"Calibri","sans-serif";text-align:justify;background:#E7E7E7;'><span style='font-size:10px;font-family:"Arial","sans-serif";color:black;'><br>&nbsp;Tout litige en relation avec l&rsquo;utilisation du site https://www.ethix-invest.com est soumis au droit fran&ccedil;ais.<br>&nbsp;En dehors des cas o&ugrave; la loi ne le permet pas, il est fait attribution exclusive de juridiction aux tribunaux comp&eacute;tents de Paris.</span></p>
                        <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:15px;font-family:"Calibri","sans-serif";'>&nbsp;</p>
                    </div>
                </div>
            </div>
</div>
@endsection